query QuerySpog($vulnerabilityID: String!) {
  findTopLevelPackagesRelatedToVulnerability(
    vulnerabilityID: $vulnerabilityID
  ) {
    __typename
    ... on CertifyVEXStatement {
      ...allCertifyVEXStatementTree
    }
    ... on Package {
      ...allPkgTree
    }
    ... on IsDependency {
      dependencyType
    }
  }
}

query FindVulnerability($purl: String!) {
  findVulnerability(purl: $purl) {
    __typename
    ... on CertifyVEXStatement {
      ...allCertifyVEXStatementTree
    }
  }
}

fragment allPkgTree on Package {
  id
  type
  namespaces {
    id
    namespace
    names {
      id
      name
      versions {
        id
        version
        qualifiers {
          key
          value
        }
        subpath
      }
    }
  }
}

fragment allCertifyVEXStatementTree on CertifyVEXStatement {
    id
    subject {
        __typename
        ... on Package {
            id
            type
            namespaces {
                id
                namespace
                names {
                    id
                    name
                    versions {
                        id
                        version
                        qualifiers {
                            key
                            value
                        }
                        subpath
                    }
                }
            }
        }
        ... on Artifact {
            id
            algorithm
            digest
        }
    }
    vulnerability {
        id
        type
        vulnerabilityIDs {
            id
            vulnerabilityID
        }
    }
    status
    vexJustification
    statement
    statusNotes
    knownSince
    origin
    collector
}