fragment allCertifyBadTree on CertifyBad {
  justification
  subject {
    __typename
    ... on Package {
      type
      namespaces {
        namespace
        names {
          name
          versions {
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
    ... on Source {
      type
      namespaces {
        namespace
        names {
          name
          tag
          commit
        }
      }
    }
    ... on Artifact {
      algorithm
      digest
    }
  }
  origin
  collector
}

query CertifyBadQ1($package: PkgSpec) {
  CertifyBad(certifyBadSpec: { subject: {package: $package}}) {
    ...allCertifyBadTree
  }
}
