fragment allCertifyVulnTree on CertifyVuln {
  id
  package {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          versions {
            id
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
  vulnerability {
    __typename
    ... on CVE {
      id
      year
      cveId
    }
    ... on OSV {
      id
      osvId
    }
    ... on GHSA {
      id
      ghsaId
    }
    ... on NoVuln {
      id
    }
  }
  metadata {
    dbUri
    dbVersion
    scannerUri
    scannerVersion
    origin
    collector
  }
}

query CertifyVuln($package: PkgSpec) {
  CertifyVuln(certifyVulnSpec: {package: $package}) {
    ...allCertifyVulnTree
  }
}
