fragment allCertifyVuln on CertifyVuln {
  package {
      type
      namespaces {
        namespace
        names {
          name
          versions {
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
  vulnerability {
    __typename
    ... on CVE {
      year
     cveId{
      id
    }
    }
    ... on OSV {
     osvId{
      id
    }
    }
    ... on GHSA {
      ghsaId{
        id
      }
    }
  }
  dbUri
  dbVersion
  scannerUri
  scannerVersion
  timeScanned
  origin
  collector
}

query CertifyVuln($package: PkgSpec) {
  CertifyVuln(certifyVulnSpec: {package: $package}) {
    ...allCertifyVuln
  }
}
