fragment allIsDependencyTree on IsDependency {
  justification
  package {
    type
    namespaces {
      namespace 
      names {
        name
        versions {
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
dependentPackage {
      type
    namespaces {
      namespace 
      names {
        name
        versions {
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
versionRange
origin
collector
}

query GetDependencies($package: PkgSpec) {
  IsDependency(isDependencySpec: {package: $package}) {
    ...allIsDependencyTree
  }
}

query IsDependent($package: PkgNameSpec, $version: String) {
  IsDependency(isDependencySpec: {dependentPackage: $package, versionRange: $version}) {
    ...allIsDependencyTree
  }
}
