fragment allPkgTree on Package {
  id
  type
  namespaces {
    id
    namespace
    names {
      id
      name
      versions {
        id
        version
        qualifiers {
          key
          value
        }
        subpath
      }
    }
  }
}

mutation insertMaven {
  ingestPackage(pkg: {type: "maven", namespace: "io.vertx", name: "vertx-web", version: "4.3.8"}) {
    ...allPkgTree
  }
}

# all packages
query AllPackages {
  packages(pkgSpec: {}) {
    ...allPkgTree
  }
}


query GetPackages($package: PkgSpec) {
  packages(pkgSpec: $package) {
    ...allPkgTree
  }
}
