fragment allCertifyGoodTree on CertifyGood {
  id
  justification
  subject {
    __typename
    ... on Package {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          versions {
            id
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
    ... on Source {
      id
      type
      namespaces {
        namespace
        names {
          name
          tag
          commit
        }
      }
    }
    ... on Artifact {
      id
      algorithm
      digest
    }
  }
  origin
  collector
}

mutation IngestCertifyGood($subject: PackageSourceOrArtifactInput!, $pkgMatchType: MatchFlags!, $certifyGood: CertifyGoodInputSpec!) {
  ingestCertifyGood(
    subject: $subject
    pkgMatchType: $pkgMatchType
    certifyGood: $certifyGood
  ) {
    id
  }
}

query QueryCertifyGood($certifyGoodSpec: CertifyGoodSpec!) {
  CertifyGood(certifyGoodSpec: $certifyGoodSpec) {
    ... allCertifyGoodTree
  }
}

