fragment allCertifyVulnTree on CertifyVuln {
    id
    package {
        id
        type
        namespaces {
            id
            namespace
            names {
                id
                name
                versions {
                    id
                    version
                    qualifiers {
                        key
                        value
                    }
                    subpath
                }
            }
        }
    }
    vulnerability {
        id
        type
        vulnerabilityIDs {
            id
            vulnerabilityID
        }
    }
    metadata {
        dbUri
        dbVersion
        scannerUri
        scannerVersion
        timeScanned
        origin
        collector
        documentRef
    }
}

mutation IngestCertifyVuln($package: IDorPkgInput!, $vulnerability: IDorVulnerabilityInput!, $meta: ScanMetadataInput!) {
    ingestCertifyVuln(
        pkg: $package
        vulnerability: $vulnerability
        certifyVuln: $meta
    )
}

query QueryCertifyVuln($certifyVulnSpec: CertifyVulnSpec!) {
    CertifyVuln(certifyVulnSpec: $certifyVulnSpec) {
        ...allCertifyVulnTree
    }
}

query QueryCertifyVulnById($id: String!) {
    CertifyVuln(certifyVulnSpec: {vulnerability: { vulnerabilityID: $id}}) {
        ...allCertifyVulnTree
    }
}
