fragment allPkgTree on Package {
  id
  type
  namespaces {
    id
    namespace
    names {
      id
      name
      versions {
        id
        version
        qualifiers {
          key
          value
        }
        subpath
      }
    }
  }
}

mutation IngestPackage($package: PkgInputSpec!) {
  ingestPackage(pkg: $package) {
    id
  }
}

query QueryPackages($package: PkgSpec!) {
  packages(pkgSpec: $package) {
    ...allPkgTree
  }
}

