fragment allPkgTree on Package {
    id
    type
    namespaces {
        id
        namespace
        names {
            id
            name
            versions {
                id
                version
                qualifiers {
                    key
                    value
                }
                subpath
            }
        }
    }
}

mutation IngestPackage($package: IDorPkgInput!) {
    ingestPackage (pkg: $package) {
        packageTypeID
        packageNamespaceID
        packageNameID
        packageVersionID
    }
}

query QueryPackages($package: PkgSpec!) {
    packages(pkgSpec: $package) {
        ...allPkgTree
    }
}

