fragment allCertifyBadTree on CertifyBad {
  id
  justification
  subject {
    __typename
    ... on Package {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          versions {
            id
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
    ... on Source {
      id
      type
      namespaces {
        namespace
        names {
          name
          tag
          commit
        }
      }
    }
    ... on Artifact {
      id
      algorithm
      digest
    }
  }
  origin
  collector
}

mutation IngestCertifyBad($subject: PackageSourceOrArtifactInput!, $pkgMatchType: MatchFlags!, $certifyBad: CertifyBadInputSpec!) {
  ingestCertifyBad(
    subject: $subject
    pkgMatchType: $pkgMatchType
    certifyBad: $certifyBad
  )
}

query QueryCertifyBad($certifyBadSpec: CertifyBadSpec!) {
  CertifyBad(certifyBadSpec: $certifyBadSpec) {
    ... allCertifyBadTree
  }
}
